// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;     
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-xPpnCVnVK7eOUsU22xJwQdX2S5WLRI',
    appId: '1:126032388224:web:e8f4c40c0e47c29076c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    authDomain: 'ms-supplier-3c238.firebaseapp.com',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    measurementId: 'G-YYGCLVMMRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjT5Y7I--NFGIAHqnb-KPdUh07Ptg7sck',
    appId: '1:126032388224:android:5e713af1bb42e24b76c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGUL-HGPfTtylJSKu-_u_A7BwKGxYhkQ',
    appId: '1:126032388224:ios:d704d21de2bee23976c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    androidClientId: '126032388224-t2regf644eheeprrq5bvdrasp2nsno4b.apps.googleusercontent.com',
    iosClientId: '126032388224-qahrg3eqs6bvm9csu5ug4iisghrkj0ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.msCustomersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqGUL-HGPfTtylJSKu-_u_A7BwKGxYhkQ',
    appId: '1:126032388224:ios:d704d21de2bee23976c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    androidClientId: '126032388224-t2regf644eheeprrq5bvdrasp2nsno4b.apps.googleusercontent.com',
    iosClientId: '126032388224-qahrg3eqs6bvm9csu5ug4iisghrkj0ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.msCustomersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1-xPpnCVnVK7eOUsU22xJwQdX2S5WLRI',
    appId: '1:126032388224:web:5470b803ec5a9d5676c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    authDomain: 'ms-supplier-3c238.firebaseapp.com',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    measurementId: 'G-3GMDWJJGRD',
  );
}
