// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-xPpnCVnVK7eOUsU22xJwQdX2S5WLRI',
    appId: '1:126032388224:web:af8bedbe942d72a676c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    authDomain: 'ms-supplier-3c238.firebaseapp.com',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    measurementId: 'G-QESPTRQN2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjT5Y7I--NFGIAHqnb-KPdUh07Ptg7sck',
    appId: '1:126032388224:android:9ef27946fefd020b76c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGUL-HGPfTtylJSKu-_u_A7BwKGxYhkQ',
    appId: '1:126032388224:ios:c30a21f2cb94b7b476c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    iosClientId: '126032388224-eijoikmms947kt6d67tskv7m7oraivcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSupplierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqGUL-HGPfTtylJSKu-_u_A7BwKGxYhkQ',
    appId: '1:126032388224:ios:c30a21f2cb94b7b476c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    iosClientId: '126032388224-eijoikmms947kt6d67tskv7m7oraivcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.msSupplierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1-xPpnCVnVK7eOUsU22xJwQdX2S5WLRI',
    appId: '1:126032388224:web:ff80daed335d217376c665',
    messagingSenderId: '126032388224',
    projectId: 'ms-supplier-3c238',
    authDomain: 'ms-supplier-3c238.firebaseapp.com',
    storageBucket: 'ms-supplier-3c238.appspot.com',
    measurementId: 'G-V4TKTN2L69',
  );
}
